### PR TITLE
You still have to auth with the app.

### PR DESCRIPTION
**Pull request by H644b**

### CODE REVIEW

**Comment by PeapGit** [comment]
im like 90% sure that this is just different UI for discord.

**Comment by H644b** [comment]
No I checked, when you auth the app the official discord domain is there and you allow some access to your acc like normal.

**Comment by H644b** [comment]
@PeapGit Im not denying that when you chat the interface and ui is not discord, Im saying when you auth, it still takes to the disc domain defeating the entire purpose.

**Comment by PeapGit** [comment]
yk what im leaving this to either doxr or appleflyer as they know more than me about the widget bot.

**Comment by H644b** [comment]
k

**Comment by DoxrGitHub** [comment]
apple added Auth back to stop ban evasion, sooner or later I'll remove Auth and make a channel only for widgetbot users

**Comment by H644b** [comment]
k

**Comment by H644b** [comment]
ima close this then

**Comment by H644b** [comment]
goobahhye

**Comment by DoxrGitHub** [comment]
Auth requirement lifted for now

**Pull request closed without merging**
